### PR TITLE
New gh-actions workflow to check file encodigs Closes #36

### LINKED ISSUE #36: New template to check encoding on CI
@cjyetman recently developed a new gh-workflow to
check for correct encodings. It would be nice to
add it in inst/templates/check_encodings.yml so 
we can easily reuse it with 

    use_template("check_encodings.yml", package = "r2dii.usethis")

cc @jdhoffa

### LINKED ISSUE #39: adapt file encoding PR to ignore files that have been removed
The action specification for [pr-file-encodings.yml](https://github.com/2DegreesInvesting/.github/blob/master/.github/workflow-templates/pr-file-encodings.yml) should take into account that in a PR some files will be removed completely, and therefore their encoding will be unable to be determined, and the result of the critical command might look like...

```shell
#> file --mime "${files[@]}"

R/prepare_capacity_factors_long.R:                        cannot open `R/prepare_capacity_factors_long.R' (No such file or directory)
man/prepare_capacity_factors_long.Rd:                     cannot open `man/prepare_capacity_factors_long.Rd' (No such file or directory)
tests/testthat/test-prepare_capacity_factors_long.R:      cannot open `tests/testthat/test-prepare_capacity_factors_long.R' (No such file or directory)
```

thanks to @jacobvjk for reporting here: https://github.com/2DegreesInvesting/r2dii.stress.test.data/pull/16#issuecomment-870410694

### PR DESCRIPTION
**Pull request by maurolepore**
Closes #36
Closes #39 

This PR makes r2dii.usethis the home of a workflow that before was
in the organization wide repo .github. There its behaviour was not
the expected one (that it would automatically show up in all repos
of 2DegreesInvesting) so I move it here so we can add it to any 
new repo with:

    usethis::use_template(
      "check-file-encodings.yml", package = "r2dii.usethis"
    )﻿

Notice the extension is ".yaml" and not ".yml". I don't think it
matters but ".yaml" is consistent with all templates I see at
<https://github.com/r-lib/actions/tree/master/examples>.

### CODE REVIEW

**Comment by cjyetman** [comment]
> Notice the extension is ".yaml" and not ".yml". I don't think it
> matters but ".yaml" is consistent with all templates I see at
> https://github.com/r-lib/actions/tree/master/examples.

I thought the same, but then I followed [GitHub's instructions](https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions#create-an-example-workflow), which use `.yml`.... but I'm totally indifferent about it.

**Review by cjyetman — APPROVED** [review]
lgtm

**Comment by cjyetman** [comment]
also this...
Screenshot 2021-06-30 at 08 44 15

**Comment by maurolepore** [comment]
Thanks @cjyetman I just pasted the version you shared [here](https://github.com/2DegreesInvesting/r2dii.usethis/issues/39#issuecomment-871147569) and renamed the file extension to .yml.

**Pull request merged**
