### PR TITLE
Use r2dii github repository labels

### PR DESCRIPTION
**Pull request by jdhoffa**
Here I propose a way to add some default github issues to the users active repository. 
Running this function in your active repository will ADD all the pre-defined labels, colours and descriptions to this repository, WITHOUT deleting the existing labels. 

If you wish to delete the existing labels, run `r2dii.usethis::use_r2dii_labels(delete_default = TRUE)`.

In either case, none of the existing labels will be affected. 
I leave it as a draft so that we can discuss which labels should/ shouldn't be included by default!
For now, the labels appear as follows: 
Screenshot 2021-06-11 at 15 14 59

### CODE REVIEW

**Comment by jdhoffa** [comment]
Closes #34

**Review by maurolepore — APPROVED** [review]
LGTM -- the `dontrun{}` comment may be important to address.

**Comment by jdhoffa** [comment]
I also notice tests are failing, but this is coming from `use_bridge`, which I don't touch in this PR.

**Comment by jdhoffa** [comment]
Closing because this is stale.

**Pull request closed without merging**
